server:
  port: 1025

management:
  security:
    enabled: false

dubbo:
  application:
    - name: provider-demo
      owner: zhaorui
      organization: com.dxhy.basic.dubbo
  registries:
    - address: 10.1.1.153:2181
      protocol: zookeeper
  services:
    - interface: rui.framework.dubbo.demo.service.NameService
      connections: 10
      protocols:
        - name: dubbo
          port: 20401
        - name: dubbo
          port: 20402
      timeout: 2000
    - interface: rui.framework.dubbo.demo.service.PermissionService
      connections: 10
      protocols:
        - name: dubbo
          port: 20405
        - name: dubbo
          port: 20406
      timeout: 2000
  providers:
    - threads: 200
      protocols:
        - name: dubbo
          port: 20881
        - name: dubbo
          port: 20402