server:
  port: 1025

management:
  security:
    enabled: false

dubbo:
  application:
    - name: provider-demo
      owner: zhaorui
      organization: com.dxhy.basic.dubbo
  registries:
    - address: 10.1.1.153:2181
      protocol: zookeeper
  services:
    - interface: rui.framework.dubbo.demo.service.UserService
    - interface: rui.framework.dubbo.demo.service.RoleService
    - interface: rui.framework.dubbo.demo.service.PermissionService
  providers:
    - threads: 200
      protocols:
        - name: dubbo
          port: 20881
        - name: dubbo
          port: 20402