server:
  port: 1026

management:
  security:
    enabled: false

dubbo:
  applications:
    - name: consumer-demo
      owner: zhaorui
      organization: com.dxhy.basic.dubbo
  registries:
    - address: 10.1.1.153:2181
      protocol: zookeeper
  consumers:
    - timeout: 5000
      retries: 5
  references:
    - interface: rui.framework.dubbo.demo.service.NameService
      protocol: dubbo
      consumer:
        timeout: 5000
        retries: 5