server:
  port: 1026

management:
  security:
    enabled: false

dubbo:
  applications:
    - name: consumer-demo
      owner: zhaorui
      organization: com.dxhy.basic.dubbo
  registries:
    - address: 10.1.1.153:2181
      protocol: zookeeper
  references:
    - interface: com.github.yinfujing.dubbo.demo.service.UserService
    - interface: com.github.yinfujing.dubbo.demo.service.RoleService
    - interface: com.github.yinfujing.dubbo.demo.service.PermissionService